# Setup
title:        Diary of a <s>madman</s> miner...
tagline:      Crypto Mining, Sia Hosting/Renting + Pings n Things
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       tutemwesi
  url:        http://intheether.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
